# Generated by Django 4.2.7 on 2025-11-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(verbose_name='date performed')),
                ('mileage_at_service', models.PositiveIntegerField(verbose_name='mileage at service')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cost')),
                ('service_provider', models.CharField(blank=True, max_length=200, verbose_name='service provider')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('next_due_date', models.DateField(blank=True, help_text='Next scheduled date for this maintenance', null=True, verbose_name='next due date')),
                ('next_due_mileage', models.PositiveIntegerField(blank=True, help_text='Next scheduled mileage for this maintenance', null=True, verbose_name='next due mileage')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'maintenance record',
                'verbose_name_plural': 'maintenance records',
                'ordering': ['-date_performed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('recommended_interval_km', models.PositiveIntegerField(blank=True, help_text='Recommended interval in kilometers', null=True, verbose_name='recommended interval (km)')),
                ('recommended_interval_months', models.PositiveIntegerField(blank=True, help_text='Recommended interval in months', null=True, verbose_name='recommended interval (months)')),
            ],
            options={
                'verbose_name': 'maintenance type',
                'verbose_name_plural': 'maintenance types',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='maintenance.maintenancerecord', verbose_name='maintenance record')),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'ordering': ['due_date', '-is_completed'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='maintenance.maintenancetype', verbose_name='maintenance type'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle', verbose_name='vehicle'),
        ),
    ]
