# Generated by Django 4.2.7 on 2025-11-02 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=100, verbose_name='manufacturer')),
                ('model_name', models.CharField(max_length=100, verbose_name='model')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='registration number')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('suv', 'SUV'), ('van', 'Van'), ('other', 'Other')], default='car', max_length=20, verbose_name='vehicle type')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year of manufacture')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('vin_number', models.CharField(blank=True, help_text='17-character Vehicle Identification Number', max_length=17, verbose_name='VIN number')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('current_mileage', models.PositiveIntegerField(default=0, help_text='Current mileage in kilometers', verbose_name='current mileage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'unique_together': {('user', 'registration_number')},
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/images/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle image',
                'verbose_name_plural': 'vehicle images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
