# Generated by Django 4.2.7 on 2025-11-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'vehicle image', 'verbose_name_plural': 'vehicle images'},
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image', serialize=False, to='vehicles.vehicle', verbose_name='vehicle'),
        ),
    ]
